### ISSUE TITLE
Implement Garbage Collector Statistics monitoring

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/metrics-core-hdr#5]
In first release will be supported only implementations which emit [GarbageCollectionNotificationInfo](http://docs.oracle.com/javase/8/docs/jre/api/management/extension/index.html) through [GarbageCollectorMXBean](http://docs.oracle.com/javase/8/docs/jre/api/management/extension/index.html). So at least OpenJDK and Oracle JDK will be supported. Also, the functionality for collection raw data from GC and the functionality for aggregation will be totally isolated from each other, so in future releases other types of JVM can be supported as well.

The corner metrics which should be implemented in first release:
- How many time JVM spent in stop the world (pause initiated by GC) during last N seconds.
- Rolling time window histogram for STW 
- The [top N](https://github.com/vladimir-bukhtoyarov/metrics-core-hdr/blob/1.6/src/main/java/com/github/metricscore/hdr/top/Top.java) slowest collections per each collector.
- Rolling time window counters for collected memory.
- In memory log for latest collections with configurable size.

Also it is need to implement Servlet to expose this stat in JSON via HTTP.

**Comment by mkotelba** [comment]
I'm actively working on something very similar for GC events, in addition to doing a better job collecting Metrics vs. the various Platform Management MX beans than the metrics-jvm module does.

FYI, the classes in com.sun.management are in fact public / documented / meant to be used by applications, ... but, only if you use Oracle's JVM; see [Monitoring and Management for the Java Platform](http://docs.oracle.com/javase/8/docs/technotes/guides/management/index.html) and the [API](http://docs.oracle.com/javase/8/docs/jre/api/management/extension/index.html).

Is the OpenJDK requirement set in stone?

**Comment by vladimir-bukhtoyarov** [comment]
@mkotelba I have updated issue description. The Oracle JDK will be supported as well.

**Comment by vladimir-bukhtoyarov** [comment]
This functionality will be implemented in another library [gc-monitor](https://github.com/vladimir-bukhtoyarov/gc-monitor/issues/1)
