### ISSUE TITLE
Publication of artifacts to Maven Central

### ISSUE THREAD

**Issue by mkotelba** [vladimir-bukhtoyarov/metrics-core-hdr#6]
It would be quite nice if the project artifacts were published to Maven Central in addition to Bintray.

**Comment by vladimir-bukhtoyarov** [comment]
I will do it.

**Comment by vladimir-bukhtoyarov** [comment]
Publishing to Maven central will be implemented since [version 2.0](https://github.com/vladimir-bukhtoyarov/metrics-core-hdr/issues/7)

**Comment by vladimir-bukhtoyarov** [comment]
So, I close this issue as duplicate for #7
